apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: banking-system
  labels:
    app: transaction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: banking-transaction-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8003
              name: http
          envFrom:
            - configMapRef:
                name: transaction-service-config
            - secretRef:
                name: transaction-service-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 25
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 45
            periodSeconds: 20
          resources:
            limits:
              memory: 256Mi
              cpu: 250m
            requests:
              memory: 128Mi
              cpu: 100m
