apiVersion: v1
kind: Secret
metadata:
  name: transaction-service-secret
  namespace: banking-system
  labels:
    app: transaction-service
type: Opaque
stringData:
  DATABASE_URL: "postgresql://txn_user:txn_pass@transaction-db:5432/transaction_db"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
