apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: banking-system
  labels:
    app: transaction-service
spec:
  type: NodePort
  selector:
    app: transaction-service
  ports:
    - name: http
      port: 8003
      targetPort: 8003
